### ISSUE TITLE
Certs fail to renew

### ISSUE THREAD

**Issue by anondev-sudo** [j122j/reverseproxy#10]
Check last messages here https://github.com/j122j/reverseproxy/issues/9
The issue was not still resolved, that route for challenge should be also in https block

**Comment by anondev-sudo** [comment]
https://github.com/j122j/reverseproxy/issues/9#issuecomment-1019485857

**Comment by jvvan** [comment]
I have taken a look into this, and you were correct. ACME Redirect was needed in the https block as well (for some reason).
I just published a new version. Upgrade and follow https://github.com/j122j/reverseproxy/tree/master#rebuilding-nginx-configurations
