### ISSUE TITLE
Returning []

### ISSUE THREAD

**Issue by Hiekki4** [j122j/reverseproxy#11]
When I try to create a proxy, the api returns [].

**Comment by j122j** [comment]
It looks like you are sending a GET request instead of POST thus it will return available proxies which are none.

**Comment by Hiekki4** [comment]
I send POST

**Comment by jvvan** [comment]
You'll need to provide a code example.

**Comment by Hiekki4** [comment]
I used the insomnia

**Comment by jvvan** [comment]
Try again and screenshot the program and result

**Comment by Hiekki4** [comment]
https://i.imgur.com/sginmpX.png
