### ISSUE TITLE
Revoke SSL cert when proxy is deleted

### ISSUE THREAD

**Issue by anondev-sudo** [j122j/reverseproxy#4]
SSL cert should be revoked using `certbot revoke --cert-name <DOMAIN>` when you delete proxy and cert file should be removed too.

**Comment by anondev-sudo** [comment]
@j122j Can you make this?
Maybe just make option `delete_cert` that is false by default. When you add `?delete_cert=true` to the request url, use `certbot revoke --cert-name domain` after restarting nginx (to prevent it from crashing because cert file was not found) and then delete the file of the certificate.

**Comment by j122j** [comment]
In version v1.1.0, certificates are deleted by default when you delete a proxy.
