### ISSUE TITLE
Not creating the proxy 

### ISSUE THREAD

**Issue by Hiekki4** [j122j/reverseproxy#6]
Could not reload nginx, deleting proxy: <DOMAIN>

**Comment by Hiekki4** [comment]
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by Hiekki4** [comment]
How can I resolve this issue?

**Comment by j122j** [comment]
I am not sure what is causing this bug, a few people are using this in production and it seems to work just fine. Try to restart Nginx yourself using `systemctl restart nginx` and try again. Other than that I have no idea what can be causing this issue.
