### ISSUE TITLE
Add database

### ISSUE THREAD

**Issue by anondev-sudo** [j122j/reverseproxy#7]
There should be added json or sqlite file database so you can store the information about proxies there and then make API endpoint /proxies/:domain to get more info about the proxy like target, domain, cert expiration, ...
and option when you make request to /proxies?defailed=true, dipslay more info about the proxies in array

**Comment by j122j** [comment]
In version v1.1.0, a database has not been added. However, metadata is now included in every configuration and you can get the target and whether SSL is enabled.
