### ISSUE TITLE
Certs are not auto renewed

### ISSUE THREAD

**Issue by anondev-sudo** [j122j/reverseproxy#9]
Hi, I recently get email from let's encrypt that certs will expire soon that were created using this. When I manually run certbot renew it throws errors that it can't complete the challenge (404 error). I think that it can't renew it because there is reverse proxy and files are not located in some directory, certs for pterodactyl and controlpanel is normally auto renewed.

I used `certbot certonly --nginx -d domain.com` to manually renew the certs.

**Comment by j122j** [comment]
You can now use the auto-renew feature provided by certbot if you have the v1.1.0 version installed.

**Comment by anondev-sudo** [comment]
How to use it?

**Comment by anondev-sudo** [comment]
When I run certbot renew I get this kind of errors:
![](https://cdn.pinglik.eu/u/files/8QkRFewde4)
![](https://cdn.pinglik.eu/u/files/nTrxKacuJd)

It can't reach the challenge because the sites are proxied, not pointed to directory in /var/www

**Comment by j122j** [comment]
Did you update and run the migrate script?

**Comment by anondev-sudo** [comment]
> Did you update and run the migrate script? After that restart nginx.

I did this

**Comment by anondev-sudo** [comment]
Must /var/www/html be empty?

**Comment by anondev-sudo** [comment]
I assume that it failed to renew because ACME-challenge location is not in 443 server (ssl) block in the template nginx config.
![image](https://user-images.githubusercontent.com/85408287/150680770-a0418ced-a3fe-4637-9ce4-c17e77eef096.png)

Got it from https://rajeeshknambiar.wordpress.com/2021/05/08/letsencrypt-certificate-renewal-nginx-with-reverse-proxy/

**Comment by anondev-sudo** [comment]
@j122j Check my messages above.

Also question: For what purpose can be streams used? Can it be used to connect custom domain to MongoDB and other databases hosted on ptero?
